### ISSUE TITLE
?!居然遇到了同行大佬！！！

### ISSUE THREAD

**Issue by lyimoexiao** [biliblihuorong/Bicarbon-MES#1]
啊哈，没想到在这也能遇到同一个赛项的~

24年国赛学牲在此

（什么LJ参阅写的想吐血）

**Comment by biliblihuorong** [comment]
大佬大佬，我已经对那个参阅不想回忆了

**Comment by lyimoexiao** [comment]
> 大佬大佬，我已经对那个参阅不想回忆了

嘶，这就很。。。

我们现在一位RP仙人，一位后端，一个前端废物

救救孩子（

![214C21B3D3E0555F9E42CDC89C4ED246](https://github.com/biliblihuorong/Bicarbon-MES/assets/51842260/2e46b981-94ba-4e91-abd7-0d2494424145)

**Comment by biliblihuorong** [comment]
RP? 
我只是后端的，帮不了你啥，后端有些东西我已经写成博文发布了。

**Comment by lyimoexiao** [comment]
> RP? 我只是后端的，帮不了你啥，后端有些东西我已经写成博文发布了。

挺好的，可惜我是臭前端（

**Comment by biliblihuorong** [comment]
> > RP? 我只是后端的，帮不了你啥，后端有些东西我已经写成博文发布了。
> 
> 挺好的，可惜我是臭前端（

确实蛮辛苦的，前端工作量很大（只能说算相对吧），所以 RP ？ 是什么意思？

**Comment by yanheya** [comment]
> > > RP? 我只是后端的，帮不了你啥，后端有些东西我已经写成博文发布了。
> > 
> > 
> > 挺好的，可惜我是臭前端（
> 
> 确实蛮辛苦的，前端工作量很大（只能说算相对吧），所以 RP ？ 是什么意思？

Axure rp，原型图，画起来真的很烦！！！

**Comment by biliblihuorong** [comment]
> > > > RP? 我只是后端的，帮不了你啥，后端有些东西我已经写成博文发布了。
> > > 
> > > 
> > > 挺好的，可惜我是臭前端（
> > 
> > 
> > 确实蛮辛苦的，前端工作量很大（只能说算相对吧），所以 RP ？ 是什么意思？
> 
> Axure rp，原型图，画起来真的很烦！！！

这个简写。。。。 彳亍
所以你和他是一队的？

**Comment by lyimoexiao** [comment]
> > > > > RP? 我只是后端的，帮不了你啥，后端有些东西我已经写成博文发布了。
> > > > 
> > > > 
> > > > 挺好的，可惜我是臭前端（
> > > 
> > > 
> > > 确实蛮辛苦的，前端工作量很大（只能说算相对吧），所以 RP ？ 是什么意思？
> > 
> > Axure rp，原型图，画起来真的很烦！！！
> 
> 这个简写。。。。 彳亍
> 所以你和他是一队的？

猜中了（）
